-- MySQL Script generated by MySQL Workbench
-- Sat May  6 12:36:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bienestar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS Bienestar;

-- -----------------------------------------------------
-- Schema Bienestar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS Bienestar DEFAULT CHARACTER SET utf8 ;
USE Bienestar ;

-- -----------------------------------------------------
-- Table Bienestar.Ambulancia
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Ambulancia ;

CREATE TABLE IF NOT EXISTS Bienestar.Ambulancia (
  idAmbulancia VARCHAR(6) NOT NULL,
  PRIMARY KEY (idAmbulancia))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Persona
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Persona ;

CREATE TABLE IF NOT EXISTS Bienestar.Persona (
  perID INT UNSIGNED NOT NULL,
  perNombre VARCHAR(45) NOT NULL,
  perApellido VARCHAR(45) NOT NULL,
  perDireccion VARCHAR(45) NOT NULL DEFAULT 'Sin Dirección',
  perBarrio VARCHAR(45) NOT NULL DEFAULT 'Sin Barrio',
  perCiudad VARCHAR(45) NOT NULL DEFAULT 'Bogotá',
  perTipoVivienda ENUM("Casa", "Apartamento", "Apartaestudio", "Finca") NOT NULL DEFAULT 'Casa',
  perLocalidad VARCHAR(45) NOT NULL DEFAULT 'Sin Localidad',
  perEmail VARCHAR(150) NULL,
  perEntidadSalud VARCHAR(45) NOT NULL DEFAULT 'N.E',
  perProcedencia VARCHAR(45) NOT NULL DEFAULT 'N.E',
  perSede VARCHAR(20) NOT NULL DEFAULT 'Bogotá',
  perFacultad VARCHAR(50) NOT NULL DEFAULT 'No tiene',
  PRIMARY KEY (perID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX perID_UNIQUE ON Bienestar.Persona (perID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.PersonalSalud
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.PersonalSalud ;

CREATE TABLE IF NOT EXISTS Bienestar.PersonalSalud (
  salProfesion VARCHAR(45) NULL,
  salEspecializacion VARCHAR(45) NULL,
  salTipo VARCHAR(10) NOT NULL,
  salAmbulancia VARCHAR(6) NULL,
  perID INT UNSIGNED NOT NULL,
  PRIMARY KEY (perID),
  CONSTRAINT fk_PersonalSalud_Ambulancia1
    FOREIGN KEY (salAmbulancia)
    REFERENCES Bienestar.Ambulancia (idAmbulancia)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PersonalSalud_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE INDEX fk_PersonalSalud_Ambulancia1_idx ON Bienestar.PersonalSalud (Ambulancia_id ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Urgencia
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Urgencia ;

CREATE TABLE IF NOT EXISTS Bienestar.Urgencia (
  urgID INT NOT NULL,
  perID INT UNSIGNED NOT NULL,
  Ambulancia VARCHAR(6) NULL,
  idUrgencia INT NOT NULL,
  urgFecha DATETIME NOT NULL,
  urgTipo TINYINT NOT NULL,
  urgRiesgo TINYINT NOT NULL,
  urgDiagnostico VARCHAR(45) NOT NULL,
  urgTraslado VARCHAR(45) NOT NULL,
  urgHoraRecogida DATETIME NOT NULL,
  urgHoraDejada DATETIME NOT NULL,
  PRIMARY KEY (urgID, perID),
  CONSTRAINT fk_Urgencia_Ambulancia1
    FOREIGN KEY (Ambulancia)
    REFERENCES Bienestar.Ambulancia (idAmbulancia)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Urgencia_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Urgencia_Ambulancia1_idx ON Bienestar.Urgencia (Ambulancia ASC) VISIBLE;

CREATE UNIQUE INDEX urgID_UNIQUE ON Bienestar.Urgencia (urgID ASC) VISIBLE;

CREATE INDEX fk_Urgencia_Persona1_idx ON Bienestar.Urgencia (perID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Incapacidad
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Incapacidad ;

CREATE TABLE IF NOT EXISTS Bienestar.Incapacidad (
  IncapacidadID INT NOT NULL AUTO_INCREMENT,
  perID INT UNSIGNED NOT NULL,
  incFecha DATE NOT NULL,
  incEnfermedad VARCHAR(45) NOT NULL,
  incDias TINYINT NOT NULL,
  incConvalidada BIT NOT NULL,
  PRIMARY KEY (IncapacidadID),
  CONSTRAINT fk_Incapacidad_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.PerfilRiesgoIntegral
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.PerfilRiesgoIntegral ;

CREATE TABLE IF NOT EXISTS Bienestar.PerfilRiesgoIntegral (
  perID INT UNSIGNED NOT NULL,
  perFecha DATE NOT NULL,
  perSaludFisica INT NOT NULL,
  perSaludPsicologica INT NOT NULL,
  PRIMARY KEY (perID),
  CONSTRAINT fk_PerfilRiesgoIntegral_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Resultados
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Resultados ;

CREATE TABLE IF NOT EXISTS Bienestar.Resultados (
  PerfilRiesgoIntegral_id INT NOT NULL,
  resPregunta VARCHAR(45) NOT NULL,
  resRespuesta VARCHAR(45) NOT NULL,
  PRIMARY KEY (PerfilRiesgoIntegral_id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Discapacidad
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Discapacidad ;

CREATE TABLE IF NOT EXISTS Bienestar.Discapacidad (
  discapacidadID INT NOT NULL AUTO_INCREMENT,
  perID INT UNSIGNED NOT NULL,
  disNombre VARCHAR(45) NOT NULL,
  disVerificado BIT NOT NULL,
  PRIMARY KEY (discapacidadID),
  CONSTRAINT fk_Discapacidad_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Cargo
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Cargo ;

CREATE TABLE IF NOT EXISTS Bienestar.Cargo (
  carID INT UNSIGNED NOT NULL,
  carNombre ENUM('Profesor', 'Estudiante', 'Rector', 'Directivo', 'Jefe', 'Empleado', 'Ninguno', 'Otro', 'Vicerrector') NOT NULL DEFAULT 'Profesor',
  PRIMARY KEY (carID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX perID_UNIQUE ON Bienestar.Cargo (carID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.CitaMedica
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.CitaMedica ;

CREATE TABLE IF NOT EXISTS Bienestar.CitaMedica (
  idCitaMedica INT NOT NULL,
  doctorID INT UNSIGNED NOT NULL,
  pacienteID INT UNSIGNED NULL,
  citFecha DATETIME NOT NULL,
  citEspecialidad VARCHAR(45) NOT NULL,
  citDiagnostico VARCHAR(80) NULL,
  PRIMARY KEY (idCitaMedica),
  CONSTRAINT fk_CitaMedica_Persona1
    FOREIGN KEY (pacienteID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CitaMedica_PersonalSalud1
    FOREIGN KEY (doctorID)
    REFERENCES Bienestar.PersonalSalud (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_CitaMedica_Persona1_idx ON Bienestar.CitaMedica (pacienteID ASC) VISIBLE;

CREATE INDEX fk_CitaMedica_PersonalSalud1_idx ON Bienestar.CitaMedica (doctorID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.EvaluacionFisica
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.EvaluacionFisica ;

CREATE TABLE IF NOT EXISTS Bienestar.EvaluacionFisica (
  CitaMedica_id INT NOT NULL,
  evaPeso TINYINT NOT NULL,
  evaEstatura TINYINT NOT NULL,
  evaRitmoCardiaco TINYINT NOT NULL,
  evaVision TINYINT NOT NULL,
  PRIMARY KEY (CitaMedica_id),
  CONSTRAINT fk_EvaluacionFisica_CitaMedica1
    FOREIGN KEY (CitaMedica_id)
    REFERENCES Bienestar.CitaMedica (idCitaMedica)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Medicamentos
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Medicamentos ;

CREATE TABLE IF NOT EXISTS Bienestar.Medicamentos (
  CitaMedica_id INT NOT NULL,
  medNombre VARCHAR(45) NOT NULL,
  medCantidad TINYINT NOT NULL,
  medIntervalos TINYINT NOT NULL,
  PRIMARY KEY (CitaMedica_id),
  CONSTRAINT fk_Medicamentos_CitaMedica1
    FOREIGN KEY (CitaMedica_id)
    REFERENCES Bienestar.CitaMedica (idCitaMedica)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.OrdenMedica
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.OrdenMedica ;

CREATE TABLE IF NOT EXISTS Bienestar.OrdenMedica (
  CitaMedica_id INT NOT NULL,
  ordExamen VARCHAR(45) NOT NULL,
  PRIMARY KEY (CitaMedica_id),
  CONSTRAINT fk_OrdenMedica_CitaMedica1
    FOREIGN KEY (CitaMedica_id)
    REFERENCES Bienestar.CitaMedica (idCitaMedica)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.HistoriaClinica
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.HistoriaClinica ;

CREATE TABLE IF NOT EXISTS Bienestar.HistoriaClinica (
  perID INT UNSIGNED NOT NULL,
  hisFechaApertura DATE NOT NULL,
  PRIMARY KEY (perID),
  CONSTRAINT fk_HistoriaClinica_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Enfermedad
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Enfermedad ;

CREATE TABLE IF NOT EXISTS Bienestar.Enfermedad (
  HistoriaClinicaID INT UNSIGNED NOT NULL,
  enfNombre VARCHAR(45) NOT NULL,
  enfFechaInicio DATE NOT NULL,
  PRIMARY KEY (HistoriaClinicaID),
  CONSTRAINT fk_Enfermedad_HistoriaClinica1
    FOREIGN KEY (HistoriaClinicaID)
    REFERENCES Bienestar.HistoriaClinica (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Area
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Area ;

CREATE TABLE IF NOT EXISTS Bienestar.Area (
  areID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  areNombre VARCHAR(45) NOT NULL,
  areTelefono bigint NOT NULL,
  areCorreoElectronico VARCHAR(60) NOT NULL,
  areExtension INT NOT NULL,
  areEdificio VARCHAR(100) NOT NULL,
  areDescripcion LONGTEXT NOT NULL,
  PRIMARY KEY (areID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX areID_UNIQUE ON Bienestar.Area (areID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Programa
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Programa ;

CREATE TABLE IF NOT EXISTS Bienestar.Programa (
  progID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  progNombre VARCHAR(45) NOT NULL,
  Area_areID INT UNSIGNED NOT NULL,
  PRIMARY KEY (progID),
  CONSTRAINT fk_Programa_Area1
    FOREIGN KEY (Area_areID)
    REFERENCES Bienestar.Area (areID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX progID_UNIQUE ON Bienestar.Programa (progID ASC) VISIBLE;

CREATE INDEX fk_Programa_Area1_idx ON Bienestar.Programa (Area_areID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Convocatoria
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Convocatoria ;

CREATE TABLE IF NOT EXISTS Bienestar.Convocatoria (
  conv_id INT NOT NULL,
  convNombre VARCHAR(70) NOT NULL,
  convFechaApertura DATE NOT NULL,
  convFechaCierre DATE NOT NULL,
  convEstado TINYINT NOT NULL,
  convPeriodo VARCHAR(25) NULL,
  Programa_progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (conv_id, Programa_progID),
  CONSTRAINT fk_Convocatoria_Programa1
    FOREIGN KEY (Programa_progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Convocatoria_Programa1_idx ON Bienestar.Convocatoria (Programa_progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.GrupoArtisticoInstitucional
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.GrupoArtisticoInstitucional ;

CREATE TABLE IF NOT EXISTS Bienestar.GrupoArtisticoInstitucional (
  GAI_id INT NOT NULL,
  gaiRequerimientoEspacio VARCHAR(50) NOT NULL,
  gaiNombre VARCHAR(45) NOT NULL,
  gaiDisciplina VARCHAR(60) NOT NULL,
  gaiNombreDirector VARCHAR(60) NOT NULL,
  gaiRequerimientoTecnico longtext NOT NULL,
  eveCulTipo ENUM("Evento", "Actividad Lúdica", "Instrucción", "Promoción Interculturalidad", "Expresión Talentos") NOT NULL,
  eveCulDescripcion longtext NOT NULL,
  progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (GAI_id, progID),
  CONSTRAINT fk_GrupoArtisticoInstitucional_Programa1
    FOREIGN KEY (progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_GrupoArtisticoInstitucional_Programa1_idx ON Bienestar.GrupoArtisticoInstitucional (progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaGAI
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaGAI ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaGAI (
  Convocatoria_conv_id INT NOT NULL,
  GrupoArtisticoInstitucional_GAI_id INT NOT NULL,
  convGaiNombre VARCHAR(50) NOT NULL,
  convGaiDisciplina VARCHAR(45) NOT NULL,
  convGaiEntrevista DATE NOT NULL,
  PRIMARY KEY (Convocatoria_conv_id, GrupoArtisticoInstitucional_GAI_id),
  CONSTRAINT fk_ConvGAI_Convocatoria1
    FOREIGN KEY (Convocatoria_conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ConvocatoriaGAI_GrupoArtisticoInstitucional1
    FOREIGN KEY (GrupoArtisticoInstitucional_GAI_id)
    REFERENCES Bienestar.GrupoArtisticoInstitucional (GAI_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_ConvGAI_Convocatoria1_idx ON Bienestar.ConvocatoriaGAI (Convocatoria_conv_id ASC) VISIBLE;

CREATE INDEX fk_ConvocatoriaGAI_GrupoArtisticoInstitucional1_idx ON Bienestar.ConvocatoriaGAI (GrupoArtisticoInstitucional_GAI_id ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.TorneoInterno
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.TorneoInterno ;

CREATE TABLE IF NOT EXISTS Bienestar.TorneoInterno (
  toridTorneoInterno INT NOT NULL,
  torPeriodo VARCHAR(10) NOT NULL,
  torSedeFacultad VARCHAR(60) NOT NULL,
  torDeporte VARCHAR(35) NOT NULL,
  torNombreTorneo VARCHAR(90) NOT NULL,
  torEstado TINYINT NOT NULL,
  torModalidad VARCHAR(45) NULL,
  torRama VARCHAR(45) NOT NULL,
  torNivel VARCHAR(45) NULL,
  torFechaInicio DATE NOT NULL,
  torFechaFinalizacion DATE NOT NULL,
  Programa_progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (toridTorneoInterno, Programa_progID),
  CONSTRAINT fk_TorneoInterno_Programa1
    FOREIGN KEY (Programa_progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_TorneoInterno_Programa1_idx ON Bienestar.TorneoInterno (Programa_progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaCursoLibre
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaCursoLibre ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaCursoLibre (
  Convocatoria_conv_id INT NOT NULL,
  curNombre VARCHAR(45) NOT NULL,
  curTipoCurso VARCHAR(45) NOT NULL,
  curCondicion VARCHAR(45) NOT NULL,
  PRIMARY KEY (Convocatoria_conv_id),
  CONSTRAINT fk_ConvocatoriaCursoLibre_Convocatoria1
    FOREIGN KEY (Convocatoria_conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaSeleccion
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaSeleccion ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaSeleccion (
  Convocatoria_conv_id INT NOT NULL,
  convDeporte VARCHAR(45) NOT NULL,
  convLugar VARCHAR(50) NOT NULL,
  convHora TIME NOT NULL,
  PRIMARY KEY (Convocatoria_conv_id),
  CONSTRAINT fk_ConvocatoriaSeleccion_Convocatoria1
    FOREIGN KEY (Convocatoria_conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.EventoTaller
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.EventoTaller ;

CREATE TABLE IF NOT EXISTS Bienestar.EventoTaller (
  evetaidEventoTaller INT NOT NULL,
  evetaNombre VARCHAR(60) NOT NULL,
  evetaTipoEventoTaller VARCHAR(45) NOT NULL,
  eveDescripcion LONGTEXT NOT NULL,
  evetaHoraInicio DATETIME NOT NULL,
  evetaHoraFin DATETIME NOT NULL,
  evetaFecha DATE NOT NULL,
  evetaLugar VARCHAR(45) NOT NULL,
  PRIMARY KEY (evetaidEventoTaller))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Proyecto
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Proyecto ;

CREATE TABLE IF NOT EXISTS Bienestar.Proyecto (
  proyIdProyecto INT NOT NULL,
  proyNombre VARCHAR(60) NOT NULL,
  proyEjecucion DECIMAL NOT NULL,
  proyFechaInicio DATE NOT NULL,
  proyFechaFinalizacion DATE NOT NULL,
  proyPresupuesto VARCHAR(1000) NOT NULL,
  PRIMARY KEY (proyIdProyecto))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.AtencionEnSalud
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.AtencionEnSalud ;

CREATE TABLE IF NOT EXISTS Bienestar.AtencionEnSalud (
  AtencionEnSaludID INT NOT NULL AUTO_INCREMENT,
  perID INT UNSIGNED NOT NULL,
  ateFecha DATETIME NOT NULL,
  ateVerificado BIT NOT NULL,
  PRIMARY KEY (AtencionEnSaludID),
  CONSTRAINT fk_AtencionEnSalud_Persona1
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Carrera
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Carrera ;

CREATE TABLE IF NOT EXISTS Bienestar.Carrera (
  carreID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  carreNombre VARCHAR(45) NOT NULL,
  carreCreditos INT NOT NULL DEFAULT 0,
  PRIMARY KEY (carreID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX carID_UNIQUE ON Bienestar.Carrera (carreID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Estudiante
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Estudiante ;

CREATE TABLE IF NOT EXISTS Bienestar.Estudiante (
  estID INT UNSIGNED NOT NULL,
  carreID INT UNSIGNED NOT NULL,
  estEdad TINYINT UNSIGNED NOT NULL,
  estFacultad VARCHAR(45) NOT NULL,
  estPBM TINYINT NOT NULL,
  estTipoAdmision VARCHAR(20) NOT NULL,
  estEsEgresado TINYINT NOT NULL,
  estAnoGraduacion INT NULL,
  PRIMARY KEY (estID),
  CONSTRAINT fk_Estudiante_copy1_Persona_copy11
    FOREIGN KEY (estID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Estudiante_copy1_Carrera1
    FOREIGN KEY (carreID)
    REFERENCES Bienestar.Carrera (carreID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Estudiante_copy1_Persona_copy11_idx ON Bienestar.Estudiante (estID ASC) VISIBLE;

CREATE INDEX fk_Estudiante_copy1_Carrera1_idx ON Bienestar.Estudiante (carreID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaGestionAlojamiento
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaGestionAlojamiento ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaGestionAlojamiento (
  conv_id INT NOT NULL,
  cgalDireccionAlojamiento VARCHAR(100) NOT NULL DEFAULT 'Bogota',
  cgalLocalidadAlojamiento VARCHAR(100) NOT NULL DEFAULT 'Teusaquillo',
  cgalCobertura FLOAT UNSIGNED NOT NULL DEFAULT 0,
  cgalTipoVivienda ENUM('Hotel', 'Casa', 'Apartamento', 'Vivienda familiar', 'Residencia Universitaria', 'Apartaestudio', 'Habitación', 'otro') NOT NULL DEFAULT 'Habitación',
  cgalDescripcion VARCHAR(200) NOT NULL DEFAULT 'N.A',
  cgalCosto FLOAT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (conv_id),
  CONSTRAINT fk_CvGesAlojamiento_Convocatoria1
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE INDEX fk_CvGesAlojamiento_Convocatoria1_idx ON Bienestar.ConvocatoriaGestionAlojamiento (conv_id ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaGestionTransporte
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaGestionTransporte ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaGestionTransporte (
  conv_id INT NOT NULL,
  cgtCobertura FLOAT NOT NULL DEFAULT 0,
  cgtTipoTransporte ENUM('Transporte público masivo', 'otro') NOT NULL DEFAULT 'otro',
  PRIMARY KEY (conv_id),
  CONSTRAINT fk_ConvocatoriaGestionTransporte_Convocatoria1
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaGestionAlimentaria
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaGestionAlimentaria ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaGestionAlimentaria (
  conv_id INT NOT NULL,
  cgaComida ENUM('Desayuno', 'Almuerzo', 'Cena') NOT NULL DEFAULT 'Almuerzo',
  cgaLugar ENUM('Comedor central', 'Hemeroteca', 'Odontología', 'Agronomía', 'Biología', 'Ciencias Humanas', 'Ciencias Económicas', 'Matemáticas', 'otro') NOT NULL DEFAULT 'Comedor central',
  PRIMARY KEY (conv_id),
  CONSTRAINT fk_ConvocatoriaGestionAlimentaria_Convocatoria1
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.Corresponsabilidad
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Corresponsabilidad ;

CREATE TABLE IF NOT EXISTS Bienestar.Corresponsabilidad (
  idEst INT UNSIGNED NOT NULL,
  horPendCorresp TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (idEst),
  CONSTRAINT fk_Corresponsabilidad_Estudiante_copy11
    FOREIGN KEY (idEst)
    REFERENCES Bienestar.Estudiante (estID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Corresponsabilidad_Estudiante_copy11_idx ON Bienestar.Corresponsabilidad (idEst ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ActividadCorresp
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ActividadCorresp ;

CREATE TABLE IF NOT EXISTS Bienestar.ActividadCorresp (
  actCorID INT UNSIGNED NOT NULL,
  estID INT UNSIGNED NOT NULL,
  actCorActividad ENUM('académica', 'deportiva', 'cultural', 'comunitaria', 'acompañamiento', 'desarrollo institucional', 'otra') NOT NULL DEFAULT 'académica',
  actCorHoras TINYINT NOT NULL,
  PRIMARY KEY (actCorID),
  CONSTRAINT fk_ActividadCorresp_Estudiante1
    FOREIGN KEY (estID)
    REFERENCES Bienestar.Estudiante (estID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX idActividadCorresp_UNIQUE ON Bienestar.ActividadCorresp (actCorID ASC) VISIBLE;

CREATE INDEX fk_ActividadCorresp_Estudiante1_idx ON Bienestar.ActividadCorresp (estID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Programa_Tiene_Proyecto
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Programa_Tiene_Proyecto ;

CREATE TABLE IF NOT EXISTS Bienestar.Programa_Tiene_Proyecto (
  Proyecto_proyIdProyecto INT NOT NULL,
  progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (Proyecto_proyIdProyecto, progID),
  CONSTRAINT fk_Programa_has_Proyecto_Proyecto1
    FOREIGN KEY (Proyecto_proyIdProyecto)
    REFERENCES Bienestar.Proyecto (proyIdProyecto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Programa_Tiene_Proyecto_Programa1
    FOREIGN KEY (progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Programa_has_Proyecto_Proyecto1_idx ON Bienestar.Programa_Tiene_Proyecto (Proyecto_proyIdProyecto ASC) VISIBLE;

CREATE INDEX fk_Programa_Tiene_Proyecto_Programa1_idx ON Bienestar.Programa_Tiene_Proyecto (progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Programa_Tiene_EventoTaller
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Programa_Tiene_EventoTaller ;

CREATE TABLE IF NOT EXISTS Bienestar.Programa_Tiene_EventoTaller (
  idEventoTaller INT NOT NULL,
  progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (idEventoTaller, progID),
  CONSTRAINT fk_Programa_has_EventoTaller_EventoTaller1
    FOREIGN KEY (idEventoTaller)
    REFERENCES Bienestar.EventoTaller (evetaidEventoTaller)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Programa_Tiene_EventoTaller_Programa1
    FOREIGN KEY (progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Programa_has_EventoTaller_EventoTaller1_idx ON Bienestar.Programa_Tiene_EventoTaller (idEventoTaller ASC) VISIBLE;

CREATE INDEX fk_Programa_Tiene_EventoTaller_Programa1_idx ON Bienestar.Programa_Tiene_EventoTaller (progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.CursoCultural
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.CursoCultural ;

CREATE TABLE IF NOT EXISTS Bienestar.CursoCultural (
  curidCursoCultural INT NOT NULL,
  cucNombre VARCHAR(50) NOT NULL,
  cucObjetivo LONGTEXT NOT NULL,
  cucHorario VARCHAR(60) NOT NULL,
  cucLugar VARCHAR(100) NOT NULL,
  cucCupoMinimo TINYINT(30) NOT NULL,
  cucCupoMaximo TINYINT(30) NOT NULL,
  cucCategoria VARCHAR(60) NOT NULL,
  cucNivel int ,
  Programa_progID INT UNSIGNED NOT NULL,
  PRIMARY KEY (curidCursoCultural, Programa_progID),
  CONSTRAINT fk_CursoCultural_Programa1
    FOREIGN KEY (Programa_progID)
    REFERENCES Bienestar.Programa (progID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_CursoCultural_Programa1_idx ON Bienestar.CursoCultural (Programa_progID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Inscripcion
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Inscripcion ;

CREATE TABLE IF NOT EXISTS Bienestar.Inscripcion (
  Inscripcion INT NOT NULL,
  insFechaLimite DATE NOT NULL,
  insValor DOUBLE NOT NULL,
  insPeriodo VARCHAR(45) NOT NULL,
  PRIMARY KEY (Inscripcion))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.CursoCultural_has_Inscripcion
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.CursoCultural_has_Inscripcion ;

CREATE TABLE IF NOT EXISTS Bienestar.CursoCultural_has_Inscripcion (
  CursoCultural_curidCursoCultural INT NOT NULL,
  Inscripcion_Inscripcion INT NOT NULL,
  PRIMARY KEY (CursoCultural_curidCursoCultural, Inscripcion_Inscripcion),
  CONSTRAINT fk_CursoCultural_has_Inscripcion_CursoCultural1
    FOREIGN KEY (CursoCultural_curidCursoCultural)
    REFERENCES Bienestar.CursoCultural (curidCursoCultural)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CursoCultural_has_Inscripcion_Inscripcion1
    FOREIGN KEY (Inscripcion_Inscripcion)
    REFERENCES Bienestar.Inscripcion (Inscripcion)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_CursoCultural_has_Inscripcion_Inscripcion1_idx ON Bienestar.CursoCultural_has_Inscripcion (Inscripcion_Inscripcion ASC) VISIBLE;

CREATE INDEX fk_CursoCultural_has_Inscripcion_CursoCultural1_idx ON Bienestar.CursoCultural_has_Inscripcion (CursoCultural_curidCursoCultural ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Estudiante_Toma_Convocatoria
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Estudiante_Toma_Convocatoria ;

CREATE TABLE IF NOT EXISTS Bienestar.Estudiante_Toma_Convocatoria (
  idEst INT UNSIGNED NOT NULL,
  conv_id INT NOT NULL,
  PRIMARY KEY (idEst, conv_id),
  CONSTRAINT fk_Estudiante_copy1_has_Convocatoria_Estudiante_copy11
    FOREIGN KEY (idEst)
    REFERENCES Bienestar.Estudiante (estID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Estudiante_copy1_has_Convocatoria_Convocatoria1
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE INDEX fk_Estudiante_copy1_has_Convocatoria_Convocatoria1_idx ON Bienestar.Estudiante_Toma_Convocatoria (conv_id ASC) VISIBLE;

CREATE INDEX fk_Estudiante_copy1_has_Convocatoria_Estudiante_copy11_idx ON Bienestar.Estudiante_Toma_Convocatoria (idEst ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaGestionEconomica
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaGestionEconomica ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaGestionEconomica (
  conv_id INT NOT NULL,
  cgeCobertura FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (conv_id),
  CONSTRAINT fk_ConvocatoriaGestionTransporte_Convocatoria10
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.persona_cargo
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.persona_cargo ;

CREATE TABLE IF NOT EXISTS Bienestar.persona_cargo (
  perID INT UNSIGNED NOT NULL,
  carID INT UNSIGNED NOT NULL,
  PRIMARY KEY (perID, carID),
  CONSTRAINT fk_Persona_copy1_has_Cargo_Persona_copy11
    FOREIGN KEY (perID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Persona_copy1_has_Cargo_Cargo1
    FOREIGN KEY (carID)
    REFERENCES Bienestar.Cargo (carID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Persona_copy1_has_Cargo_Cargo1_idx ON Bienestar.persona_cargo (carID ASC) VISIBLE;

CREATE INDEX fk_Persona_copy1_has_Cargo_Persona_copy11_idx ON Bienestar.persona_cargo (perID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.FallaAlimentacion
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.FallaAlimentacion ;

CREATE TABLE IF NOT EXISTS Bienestar.FallaAlimentacion (
  fallAlID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  estID INT UNSIGNED NOT NULL,
  fallAlcgaComida ENUM('Desayuno', 'Almuerzo', 'Cena') NOT NULL DEFAULT 'Almuerzo',
  fallAlLugar ENUM('Comedor central', 'Hemeroteca', 'Odontología', 'Agronomía', 'Biología', 'Ciencias Humanas', 'Ciencias Económicas', 'Matemáticas', 'otro') NOT NULL DEFAULT 'Comedor central',
  fallAlFecha DATE NOT NULL,
  PRIMARY KEY (fallAlID),
  CONSTRAINT fk_FallaAlimentacion_Estudiante1
    FOREIGN KEY (estID)
    REFERENCES Bienestar.Estudiante (estID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX fallAlID_UNIQUE ON Bienestar.FallaAlimentacion (fallAlID ASC) VISIBLE;

CREATE INDEX fk_FallaAlimentacion_Estudiante1_idx ON Bienestar.FallaAlimentacion (estID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.ConvocatoriaFomentoEmprendimeinto
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.ConvocatoriaFomentoEmprendimeinto ;

CREATE TABLE IF NOT EXISTS Bienestar.ConvocatoriaFomentoEmprendimeinto (
  conv_id INT NOT NULL,
  cgemCobertura FLOAT NOT NULL DEFAULT 0,
  cgemNombreEmprend VARCHAR(60) NOT NULL,
  cgemTema VARCHAR(50) NOT NULL,
  cgemDescripcion VARCHAR(200) NOT NULL,
  PRIMARY KEY (conv_id),
  CONSTRAINT fk_ConvocatoriaGestionTransporte_Convocatoria100
    FOREIGN KEY (conv_id)
    REFERENCES Bienestar.Convocatoria (conv_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Bienestar.TiendaBienestar
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.TiendaBienestar ;

CREATE TABLE IF NOT EXISTS Bienestar.TiendaBienestar (
  tieID INT NOT NULL AUTO_INCREMENT,
  tieCiudad VARCHAR(45) NOT NULL DEFAULT 'Bogotá',
  tieDireccion VARCHAR(50) NOT NULL DEFAULT 'N.E',
  tieHorInicio TIME NOT NULL DEFAULT '08:00:00',
  tieHorFinal TIME NOT NULL DEFAULT '16:00:00',
  directorID INT UNSIGNED NOT NULL,
  jefeID INT UNSIGNED NOT NULL,
  PRIMARY KEY (tieID),
  CONSTRAINT fk_TiendaBienestar_copy1_Persona_copy11
    FOREIGN KEY (directorID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TiendaBienestar_copy1_Persona_copy12
    FOREIGN KEY (jefeID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX tiendBienID_UNIQUE ON Bienestar.TiendaBienestar (tieID ASC) VISIBLE;

CREATE INDEX fk_TiendaBienestar_copy1_Persona_copy11_idx ON Bienestar.TiendaBienestar (directorID ASC) VISIBLE;

CREATE INDEX fk_TiendaBienestar_copy1_Persona_copy12_idx ON Bienestar.TiendaBienestar (jefeID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Factura
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Factura ;

CREATE TABLE IF NOT EXISTS Bienestar.Factura (
  factID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  factFecha DATE NOT NULL,
  factHora TIME NOT NULL DEFAULT '08:00:00',
  factDetalle VARCHAR(100) NOT NULL DEFAULT 'N:A',
  tieID INT NOT NULL,
  clienteID INT UNSIGNED NOT NULL,
  PRIMARY KEY (factID),
  CONSTRAINT fk_Factura_copy1_TiendaBienestar_copy11
    FOREIGN KEY (tieID)
    REFERENCES Bienestar.TiendaBienestar (tieID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Factura_copy1_Persona_copy11
    FOREIGN KEY (clienteID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX factID_UNIQUE ON Bienestar.Factura (factID ASC) VISIBLE;

CREATE INDEX fk_Factura_copy1_TiendaBienestar_copy11_idx ON Bienestar.Factura (tieID ASC) VISIBLE;

CREATE INDEX fk_Factura_copy1_Persona_copy11_idx ON Bienestar.Factura (clienteID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.Producto
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.Producto ;

CREATE TABLE IF NOT EXISTS Bienestar.Producto (
  prodID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  prodPrecio DOUBLE NOT NULL DEFAULT 0,
  prodDetalle VARCHAR(100) NOT NULL DEFAULT 'Sin detalle',
  PRIMARY KEY (prodID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX prodID_UNIQUE ON Bienestar.Producto (prodID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.empleado_tiendaUN
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.empleado_tiendaUN ;

CREATE TABLE IF NOT EXISTS Bienestar.empleado_tiendaUN (
  tieID INT NOT NULL,
  empleadoID INT UNSIGNED NOT NULL,
  PRIMARY KEY (tieID, empleadoID),
  CONSTRAINT fk_TiendaBienestar_copy1_has_Persona_copy1_TiendaBienestar_co1
    FOREIGN KEY (tieID)
    REFERENCES Bienestar.TiendaBienestar (tieID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TiendaBienestar_copy1_has_Persona_copy1_Persona_copy11
    FOREIGN KEY (empleadoID)
    REFERENCES Bienestar.Persona (perID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_TiendaBienestar_copy1_has_Persona_copy1_Persona_copy11_idx ON Bienestar.empleado_tiendaUN (empleadoID ASC) VISIBLE;

CREATE INDEX fk_TiendaBienestar_copy1_has_Persona_copy1_TiendaBienestar__idx ON Bienestar.empleado_tiendaUN (tieID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.factura_producto
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.factura_producto ;

CREATE TABLE IF NOT EXISTS Bienestar.factura_producto (
  prodID INT UNSIGNED NOT NULL,
  factID INT UNSIGNED NOT NULL,
  PRIMARY KEY (prodID, factID),
  CONSTRAINT fk_Producto_copy1_has_Factura_copy1_Producto_copy11
    FOREIGN KEY (prodID)
    REFERENCES Bienestar.Producto (prodID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Producto_copy1_has_Factura_copy1_Factura_copy11
    FOREIGN KEY (factID)
    REFERENCES Bienestar.Factura (factID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_Producto_copy1_has_Factura_copy1_Factura_copy11_idx ON Bienestar.factura_producto (factID ASC) VISIBLE;

CREATE INDEX fk_Producto_copy1_has_Factura_copy1_Producto_copy11_idx ON Bienestar.factura_producto (prodID ASC) VISIBLE;


-- -----------------------------------------------------
-- Table Bienestar.producto_tiendaUN
-- -----------------------------------------------------
DROP TABLE IF EXISTS Bienestar.producto_tiendaUN ;

CREATE TABLE IF NOT EXISTS Bienestar.producto_tiendaUN (
  tieID INT NOT NULL,
  prodID INT UNSIGNED NOT NULL,
  PRIMARY KEY (tieID, prodID),
  CONSTRAINT fk_TiendaBienestar_copy1_has_Producto_copy1_TiendaBienestar_c1
    FOREIGN KEY (tieID)
    REFERENCES Bienestar.TiendaBienestar (tieID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TiendaBienestar_copy1_has_Producto_copy1_Producto_copy11
    FOREIGN KEY (prodID)
    REFERENCES Bienestar.Producto (prodID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_TiendaBienestar_copy1_has_Producto_copy1_Producto_copy11_idx ON Bienestar.producto_tiendaUN (prodID ASC) VISIBLE;

CREATE INDEX fk_TiendaBienestar_copy1_has_Producto_copy1_TiendaBienestar_idx ON Bienestar.producto_tiendaUN (tieID ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `Bienestar`.`Infante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`Infante` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`Infante` (
  `idPadre_o_Madre` INT UNSIGNED NOT NULL,
  `IdInfante` INT UNSIGNED NOT NULL,
  `TipoDocumento` VARCHAR(45) NULL,
  PRIMARY KEY (`IdInfante`),
  CONSTRAINT `fk_Infante_Persona1`
    FOREIGN KEY (`idPadre_o_Madre`)
    REFERENCES `Bienestar`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Infante_Persona2`
    FOREIGN KEY (`IdInfante`)
    REFERENCES `Bienestar`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Infante_Persona1_idx` ON `Bienestar`.`Infante` (`idPadre_o_Madre` ASC) VISIBLE;

CREATE INDEX `fk_Infante_Persona2_idx` ON `Bienestar`.`Infante` (`IdInfante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`InscripciónJardinInfantil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`InscripciónJardinInfantil` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`InscripciónJardinInfantil` (
  `Infante_IdInfante` INT UNSIGNED NOT NULL,
  `Sala` VARCHAR(45) NULL,
  `Fecha ingreso` VARCHAR(45) NULL,
  `Programa_progID` INT UNSIGNED NOT NULL,
  `FechaEgreso` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`Infante_IdInfante`, `Programa_progID`),
  CONSTRAINT `fk_InscripciónJardinInfantil_Infante1`
    FOREIGN KEY (`Infante_IdInfante`)
    REFERENCES `Bienestar`.`Infante` (`IdInfante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InscripciónJardinInfantil_Programa1`
    FOREIGN KEY (`Programa_progID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_InscripciónJardinInfantil_Infante1_idx` ON `Bienestar`.`InscripciónJardinInfantil` (`Infante_IdInfante` ASC) VISIBLE;

CREATE INDEX `fk_InscripciónJardinInfantil_Programa1_idx` ON `Bienestar`.`InscripciónJardinInfantil` (`Programa_progID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`InscripciónIPARM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`InscripciónIPARM` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`InscripciónIPARM` (
  `Infante_IdInfante` INT UNSIGNED NOT NULL,
  `Programa_progID` INT UNSIGNED NOT NULL,
  `Grado` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `FechaIngreso` VARCHAR(45) NULL,
  `FechaEgreso` VARCHAR(45) NULL,
  PRIMARY KEY (`Infante_IdInfante`, `Programa_progID`),
  CONSTRAINT `fk_InscripciónIPARM_Infante1`
    FOREIGN KEY (`Infante_IdInfante`)
    REFERENCES `Bienestar`.`Infante` (`IdInfante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InscripciónIPARM_Programa1`
    FOREIGN KEY (`Programa_progID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_InscripciónIPARM_Infante1_idx` ON `Bienestar`.`InscripciónIPARM` (`Infante_IdInfante` ASC) VISIBLE;

CREATE INDEX `fk_InscripciónIPARM_Programa1_idx` ON `Bienestar`.`InscripciónIPARM` (`Programa_progID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`ServicioCapellania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ServicioCapellania` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ServicioCapellania` (
  `idServicioCapellania` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `TIpoServicio` VARCHAR(45) NULL,
  `Programa_progID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idServicioCapellania`),
  CONSTRAINT `fk_ServicioCapellania_Programa1`
    FOREIGN KEY (`Programa_progID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ServicioCapellania_Programa1_idx` ON `Bienestar`.`ServicioCapellania` (`Programa_progID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`GrupoFormaciónEspiritual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`GrupoFormaciónEspiritual` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`GrupoFormaciónEspiritual` (
  `idGrupoFormaciónEspiritual` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `TemaEstudio` VARCHAR(45) NULL,
  `Programa_progID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idGrupoFormaciónEspiritual`),
  CONSTRAINT `fk_GrupoFormaciónEspiritual_Programa1`
    FOREIGN KEY (`Programa_progID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GrupoFormaciónEspiritual_Programa1_idx` ON `Bienestar`.`GrupoFormaciónEspiritual` (`Programa_progID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`VoluntariadoCapellania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`VoluntariadoCapellania` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`VoluntariadoCapellania` (
  `idVoluntariadoCapellania` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `FechaInicio` DATE NULL,
  `FechaFin` DATE NULL,
  `TipoVoluntariado` VARCHAR(45) NULL,
  `Programa_progID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVoluntariadoCapellania`),
  CONSTRAINT `fk_VoluntariadoCapellania_Programa1`
    FOREIGN KEY (`Programa_progID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VoluntariadoCapellania_Programa1_idx` ON `Bienestar`.`VoluntariadoCapellania` (`Programa_progID` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `Bienestar`.`ActividadAI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ActividadAI` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ActividadAI` (
  `actID` INT NOT NULL,
  `actNombre` VARCHAR(45) NOT NULL,
  `actTipo` VARCHAR(45) NOT NULL,
  `actFecha` DATETIME NULL,
  `actLugar` VARCHAR(45) NULL,
  `actDescripcion` LONGTEXT NOT NULL,
  `ProgramaID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`actID`),
  CONSTRAINT `fk_ActividadAI_Programa1`
    FOREIGN KEY (`ProgramaID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ActividadAI_Programa1_idx` ON `Bienestar`.`ActividadAI` (`ProgramaID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`ParticipacionActividadAI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ParticipacionActividadAI` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ParticipacionActividadAI` (
  `ActividadID` INT NOT NULL,
  `EstudianteID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ActividadID`, `EstudianteID`),
  CONSTRAINT `fk_ActividadAI_has_Estudiante_ActividadAI1`
    FOREIGN KEY (`ActividadID`)
    REFERENCES `Bienestar`.`ActividadAI` (`actID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActividadAI_has_Estudiante_Estudiante1`
    FOREIGN KEY (`EstudianteID`)
    REFERENCES `Bienestar`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ActividadAI_has_Estudiante_Estudiante1_idx` ON `Bienestar`.`ParticipacionActividadAI` (`EstudianteID` ASC) VISIBLE;

CREATE INDEX `fk_ActividadAI_has_Estudiante_ActividadAI1_idx` ON `Bienestar`.`ParticipacionActividadAI` (`ActividadID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`Asesoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`Asesoria` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`Asesoria` (
  `asID` INT NOT NULL,
  `asTipo` MEDIUMTEXT NOT NULL,
  `asArea` VARCHAR(45) NOT NULL,
  `asFecha` DATETIME NOT NULL,
  `asLugar` VARCHAR(45) NOT NULL,
  `ProgramaID` INT UNSIGNED NOT NULL,
  `EstudianteID` INT UNSIGNED NOT NULL,
  `AsesorID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`asID`, `ProgramaID`, `EstudianteID`, `AsesorID`),
  CONSTRAINT `fk_Asesoria_Programa1`
    FOREIGN KEY (`ProgramaID`)
    REFERENCES `Bienestar`.`Programa` (`progID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asesoria_Estudiante1`
    FOREIGN KEY (`EstudianteID`)
    REFERENCES `Bienestar`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asesoria_Persona1`
    FOREIGN KEY (`AsesorID`)
    REFERENCES `Bienestar`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Asesoria_Programa1_idx` ON `Bienestar`.`Asesoria` (`ProgramaID` ASC) VISIBLE;

CREATE INDEX `fk_Asesoria_Estudiante1_idx` ON `Bienestar`.`Asesoria` (`EstudianteID` ASC) VISIBLE;

CREATE INDEX `fk_Asesoria_Persona1_idx` ON `Bienestar`.`Asesoria` (`AsesorID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`ProyectoEstudiantil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ProyectoEstudiantil` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ProyectoEstudiantil` (
  `peID` INT NOT NULL,
  `peNombre` VARCHAR(45) NOT NULL,
  `peDescripcion` LONGTEXT NOT NULL,
  `peObjetivos` LONGTEXT NOT NULL,
  `peInicio` DATE NULL,
  `peFinalizacion` DATE NULL,
  PRIMARY KEY (`peID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bienestar`.`GrupoProyectoEstudiantil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`GrupoProyectoEstudiantil` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`GrupoProyectoEstudiantil` (
  `gpID` INT NOT NULL,
  `gpNombre` VARCHAR(45) NOT NULL,
  `gpLineadeAccion` VARCHAR(45) NOT NULL,
  `proyectoID` INT NOT NULL,
  PRIMARY KEY (`gpID`),
  CONSTRAINT `fk_GrupoProyectoEstudiantil_ProyectoEstudiantil1`
    FOREIGN KEY (`proyectoID`)
    REFERENCES `Bienestar`.`ProyectoEstudiantil` (`peID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GrupoProyectoEstudiantil_ProyectoEstudiantil1_idx` ON `Bienestar`.`GrupoProyectoEstudiantil` (`proyectoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`IntegranteGPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`IntegranteGPE` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`IntegranteGPE` (
  `EstudianteID` INT UNSIGNED NOT NULL,
  `GrupoID` INT NOT NULL,
  PRIMARY KEY (`GrupoID`, `EstudianteID`),
  CONSTRAINT `fk_Estudiante_has_GrupoProyectoEstudiantil_Estudiante1`
    FOREIGN KEY (`EstudianteID`)
    REFERENCES `Bienestar`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_GrupoProyectoEstudiantil_GrupoProyectoEstud1`
    FOREIGN KEY (`GrupoID`)
    REFERENCES `Bienestar`.`GrupoProyectoEstudiantil` (`gpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estudiante_has_GrupoProyectoEstudiantil_GrupoProyectoEst_idx` ON `Bienestar`.`IntegranteGPE` (`GrupoID` ASC) VISIBLE;

CREATE INDEX `fk_Estudiante_has_GrupoProyectoEstudiantil_Estudiante1_idx` ON `Bienestar`.`IntegranteGPE` (`EstudianteID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`ApoyoGP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ApoyoGP` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ApoyoGP` (
  `apID` INT NOT NULL,
  `apTipo` VARCHAR(45) NOT NULL,
  `apValor` INT NOT NULL,
  `GrupoID` INT NOT NULL,
  PRIMARY KEY (`apID`),
  CONSTRAINT `fk_ApoyoGP_GrupoProyectoEstudiantil1`
    FOREIGN KEY (`GrupoID`)
    REFERENCES `Bienestar`.`GrupoProyectoEstudiantil` (`gpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ApoyoGP_GrupoProyectoEstudiantil1_idx` ON `Bienestar`.`ApoyoGP` (`GrupoID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`ConvocatoriaPromotorConvivencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`ConvocatoriaPromotorConvivencia` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`ConvocatoriaPromotorConvivencia` (
  `convID` INT NOT NULL,
  `pcEstimuloEconomico` INT NOT NULL,
  `pcHorasRequeridas` TINYINT NOT NULL,
  `pcDuracionVinculacion` VARCHAR(45) NOT NULL,
  `pcCupos` TINYINT NOT NULL,
  `pcDescripcion` LONGTEXT NOT NULL,
  PRIMARY KEY (`convID`),
  CONSTRAINT `fk_ConvocatoriaPromotorConvivencia_Convocatoria1`
    FOREIGN KEY (`convID`)
    REFERENCES `Bienestar`.`Convocatoria` (`conv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocatoriaPromotorConvivencia_Convocatoria1_idx` ON `Bienestar`.`ConvocatoriaPromotorConvivencia` (`convID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Bienestar`.`PromotorConvivencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bienestar`.`PromotorConvivencia` ;

CREATE TABLE IF NOT EXISTS `Bienestar`.`PromotorConvivencia` (
  `ConvocatoriaID` INT NOT NULL,
  `EstudianteID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ConvocatoriaID`, `EstudianteID`),
  CONSTRAINT `fk_ConvocatoriaPromotorConvivencia_has_Estudiante_Convocatori1`
    FOREIGN KEY (`ConvocatoriaID`)
    REFERENCES `Bienestar`.`ConvocatoriaPromotorConvivencia` (`convID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvocatoriaPromotorConvivencia_has_Estudiante_Estudiante1`
    FOREIGN KEY (`EstudianteID`)
    REFERENCES `Bienestar`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocatoriaPromotorConvivencia_has_Estudiante_Estudiant_idx` ON `Bienestar`.`PromotorConvivencia` (`EstudianteID` ASC) VISIBLE;

CREATE INDEX `fk_ConvocatoriaPromotorConvivencia_has_Estudiante_Convocato_idx` ON `Bienestar`.`PromotorConvivencia` (`ConvocatoriaID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
